#!/bin/bash
#actual mode
SCREEN_MODE="_"

WORKSTATION_FIRST_SCREEN="VGA-1"
WORKSTATION_SECOND_SCREEN="HDMI-3"
LAPTOP_SCREEN="LVDS-1"

function setLaptopMode {
	if [ "$SCEEN_MODE" != "LAPTOP" ]
	then
		xrandr --output $WORKSTATION_SECOND_SCREEN --off
		xrandr --output $WORKSTATION_FIRST_SCREEN --off
		xrandr --output $LAPTOP_SCREEN --auto
		SCREEN_MODE=LAPTOP
	else 
		echo "Already in ldaptop mode => do nothing"
	fi
}

function setDesktopMode {
	if [ "$SCREEN_MODE" != "DESKTOP" ]
	then 
		xrandr --output $LAPTOP_SCREEN --off
		xrandr --output $WORKSTATION_FIRST_SCREEN --auto --primary
		xrandr --output $WORKSTATION_SECOND_SCREEN --auto
		xrandr --output $WORKSTATION_SECOND_SCREEN --right-of $WORKSTATION_FIRST_SCREEN
		SCREEN_MODE=DESKTOP
	else 
		echo "Already in desktop mode => do nothing"
	fi
}

function isVGA1Connected {
	! xrandr | grep "$WORKSTATION_FIRST_SCREEN" | grep "disconnected"
}

function isHDMI3Connected {
	! xrandr | grep "$WORKSTATION_SECOND_SCREEN" | grep "disconnected"
}

while true
do
	if [ isVGA1Connected ] && [ isHDMI3Connected ]
	then 
		setDesktopMode
	else
		setLaptopMode
	fi
	sleep 1s
done
